### PR TITLE
Switch from Optimist to Yargs

### PR DESCRIPTION
**Pull request by baumicon**
Switch from optimist to yargs to improve security

### CODE REVIEW

**Comment by vendethiel** [comment]
Does this not need any code change?

**Comment by baumicon** [comment]
@vendethiel No it doesn't. I tested it locally to confirm. Also Yargs describes itself as the successor to optimist: https://github.com/yargs/yargs

**Comment by vendethiel** [comment]
Wrt api surface i’m sure it’s fine. But I’m surprised you didn’t even swap out requires like the one here:
https://github.com/netzpirat/haml-coffee/blob/master/src/cli/command.coffee#L11

**Comment by baumicon** [comment]
> Wrt api surface i’m sure it’s fine. But I’m surprised you didn’t even swap out requires like the one here:
> https://github.com/netzpirat/haml-coffee/blob/master/src/cli/command.coffee#L11

That does need to be changed. It must have been reverted when I was doing cleanup. I'll update the pull request in the morning: `require('optimist')` -> `require('yargs')`

**Comment by baumicon** [comment]
@vendethiel I ran ./bin/haml-coffee --help to verify. We should be good to go.

**Comment by CeceliaYu** [comment]
Will this PR be merged shortly?

**Comment by vendethiel** [comment]
I think this got swept under the summer cleanup.
Thanks!

**Comment by pmweeks98** [comment]
@vendethiel @baumicon  when will the next release be? Version was bumped up in this pr but no release

**Comment by pmweeks98** [comment]
@vendethiel @baumicon pinging again on the release, hope to see one soon!

**Comment by vendethiel** [comment]
I don't think I have the means to cut a release, sadly. @netzpirat gave commit bits to several people, but the npm package only has him as a contributor: https://www.npmjs.com/package/haml-coffee
See #97 :(.

**Comment by CeceliaYu** [comment]
@vendethiel alternatively you can create a build and post to npm registry with a different name? ex. hamel-coffee-v2?

**Pull request merged**
