### PR TITLE
Bug: '@' is not compiled for '+include' context

### PR DESCRIPTION
**Pull request by fred104**
When compiling the following haml, the '@' will not be handled. I made a small fix to replace '@' with 'this.'.
```hamlc
+include 'partials/test', {title: @title, subtitle: @title.replace(/Title/, 'Subtitle')}
```

### CODE REVIEW

**Comment by vendethiel** [comment]
Is that part not coffeescript-compiled?

**Comment by vendethiel** [comment]
I think if it’s not, it should be. Your solution breaks cases like `include file, {title: "@twitter"}`

**Comment by fred104** [comment]
Oh, right! Better to use coffeescript compiler. Let me try.

**Comment by fred104** [comment]
@vendethiel How about this?

**Comment by fred104** [comment]
@vendethiel How about this?

**Comment by vendethiel** [comment]
It probably breaks on multiline (with \) but I’m gonna call YAGNI.

Thanks for the PR with tests!

**Comment by vendethiel** [comment]
I don’t even know who has the permissions on npm

**Comment by fred104** [comment]
Wow! ok! That's fine.

**Pull request merged**
