### PR TITLE
Fix bug passing down hyphenateDataAttrs

### PR DESCRIPTION
**Pull request by martynjames**
It seems like the flag for `hyphenateDataAttrs` was accidentally set to `format` when not overridden.

### CODE REVIEW

**Comment by vendethiel** [comment]
Nice catch indeed.

**Comment by vendethiel** [comment]
Not sure why the build is failing though?

**Comment by martynjames** [comment]
Looks like travis build has a problem with some of the transient dependencies during the `npm install` stage... a little odd because the version appearing to be requested appears to be present in the "available" list... will try to investigate when able

**Comment by sebastiandeutsch** [comment]
That would be nice. Tell me when you figured out why Travis is whining.

**Comment by vendethiel** [comment]
seems like the build is failing :/

**Comment by martynjames** [comment]
Yes, that’s what I’m trying to fix - of course it’s building locally, so I have to try multiple things and force the build to happen on the travis server to see when it is resolved - I imagine you’ll see a few more as I’m trying different things.


Marty

**Comment by vendethiel** [comment]
> Yes, that’s what I’m trying to fix - of course it’s building locally, so I have to try multiple things and force the build to happen on the travis server to see when it is resolved - I imagine you’ll see a few more as I’m trying different things.

Travis is building Node 0.10, maybe that's the issue?

**Comment by martynjames** [comment]
Oh, good idea - I’ve been trying to update the dependencies within package.json; IU’ll try just upgrading node within the .travis.yml file

M

**Comment by martynjames** [comment]
Well, looks like it passed, but I'm not sure it's right looking at the travis log... have to go back to buy day job for a while

**Comment by sebastiandeutsch** [comment]
Looks good now. Merged it.

**Pull request merged**
